version: '3.1'

services:

  db_wallet:
    container_name: db_wallet
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    image: postgres:15-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    command: 
      - 'postgres'
      - '-c'
      - 'port=${POSTGRES_PORT}'
    volumes:
      - db_wallet_vol:/var/lib/postgresql/data
    networks:
      - server_net

  wallet:
    container_name: wallet
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db_wallet
    networks:
      - server_net
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USE_SSL: ${POSTGRES_USE_SSL}
      CONN_HOST: ${CONN_HOST}
    ports:
      - ${CONN_HOST}:${CONN_HOST}
    volumes:
      - .:/wallet

volumes:
  db_wallet_vol: {}

networks:
  server_net:
    driver: bridge