version: '3.1'

services:

  db_wallet:
  # docker-compose --env-file ./config.env up -d
    container_name: db_wallet
    env_file:
      - ./config.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    image: postgres:15-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    command: 
      - 'postgres'
      - '-c'
      - 'port=${POSTGRES_PORT}'
    volumes:
      - db_wallet_vol:/var/lib/postgresql/data
    networks:
      - server_net

volumes:
  db_wallet_vol: {}

networks:
  server_net:
    driver: bridge